subtraction feature added
rahuldahal/hacktoberfest pull request #11
Opened 2023-10-09 00:47 UTC by milanbhandari047

---
name: Pull Request
about: Create a pull request to contribute to this repository
title: ''
labels: ''
assignees: ''
---

**Is your pull request related to an issue?**

If so, please link the issue here: [Link to the issue]

**Describe your Pull Request**

A clear and concise description of what you have done and why.

**Changes Made**

A brief summary of the changes you made.

**Screenshots**

If applicable, add screenshots to showcase the changes.

**Checklist**

- [ ] I have tested my changes thoroughly.
- [ ] My code follows the project's coding guidelines.
- [ ] I have added necessary documentation (if applicable).
- [ ] I have updated the README (if applicable).
- [ ] All new and existing tests passed.
- [ ] I have signed the Contributor License Agreement.

**Additional Comments**

Any additional information or context.

**Related Issues**

- Fixes #[Issue Number]
- Closes #[Issue Number]

2023-10-09 11:06 UTC, rahuldahal requested changes
I have commented on the files and changes are expected.

2023-10-09 11:06 UTC, rahuldahal commented on cpp/addition.cpp
> +    // Step 2: Performing subtraction
The comment says *subtraction*, but the code performs *addition*.

2023-10-09 11:06 UTC, rahuldahal commented on cpp/addition
delete these binary files(files generated after compilation). Only commit the files that have the source code and not the compiled binary.

2023-10-09 11:06 UTC, rahuldahal commented on cpp/multip;ication.cpp
**Rename** the file name correctly. Don't rush my friend, you have plenty of time.

2023-10-09 11:06 UTC, rahuldahal commented on cpp/subtraction
Remove this binary file as well

2023-10-09 13:12 UTC, rahuldahal requested changes

2023-10-09 13:12 UTC, rahuldahal commented on multiplication.cpp
Remove this! It is already on cpp/multiplication.cpp

2023-10-09 13:12 UTC, rahuldahal commented on cpp/subtraction
Asked you to delete this and addition!

2023-10-09 13:12 UTC, rahuldahal commented on cpp/addition
Asked you to delete this and subtraction!

2023-10-10 03:59 UTC, rahuldahal requested changes
remove the `.vscode` folder from the commit.
dot folders/files might be hidden in the explorer.
From the command line do the following:
```bash
git rm -r .vscode
git commit -m "removed .vscode settings"
git push -u origin main
```
Then delete this PR and create a new one.

2023-10-10 04:00 UTC, rahuldahal commented
@milanbhandari047 Don't be frustrated because of all the changes I've been requesting. If I were you, I would see this as a new learning opportunity. Happy coding 🥂

2023-10-10 05:01 UTC, milanbhandari047 commented
> remove the `.vscode` folder from the commit. dot folders/files might be hidden in the explorer. From the command line do the following:
> 
> ```shell
> git rm -r .vscode
> git commit -m "removed .vscode settings"
> git push -u origin main
> ```
> 
> Then delete this PR and create a new one.

@rahuldahal  can you help me how to delete the PR?

2023-10-10 05:03 UTC, closed without merging